### ISSUE TITLE
Publish vortaro.org on Github

### ISSUE THREAD

**Issue by nicolasmaia** [fisxoj/dotemacs#2]
Apologies for the non-project related issue, but it would be great to have the software of vortaro.org published in Github as well. Thanks!

**Comment by fisxoj** [comment]
Hah!

I didn't expect anyone to find it this quickly!

That's certainly the intention, though. So, don't worry on that count.

**Comment by nicolasmaia** [comment]
To be honest I found it by accident when I mistyped the PIV URL hahaha

But I remember the vortaro.org domain was on sale some weeks ago, so I figured it must be new

**Comment by fisxoj** [comment]
sorry I'm taking so long on this.  I need to move a... not very mature web framework... that I've been hacking on to a more public place otherwise the code isn't useful to other people.  I just haven't had time/am slightly ashamed of that code. :blush: 

I'll try to get it out there by the new year, even if I don't have the framework published yet.  Then, I'd love collaborators!

**Comment by fisxoj** [comment]
@picsi Sorry this took so long for no reason, I've been using my own framework under the hook and felt (still feel) a bit ashamed about that, but now things are published: https://github.com/fisxoj/vortaro

Please feel free to come over to that repo and pitch whatever improvements you'd like!  (And thank you for the interest)
